version: '3.7'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.0
    container_name: siac_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app_siac_net

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: siac_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "1029:80"
      - "2021:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app_siac_net

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: siac_db
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: db_siac_v1
      MYSQL_ROOT_PASSWORD: W3-4re_Start1nG
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app_siac_net

#Docker Networks
networks:
  app_siac_net:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
